---
html_document:
  toc: yes
title: "<center> The Project"
toc_float: yes
---
  

  
### Introduction 
  
Online shopping is an indispensable thing in modern people’s life. People can sit at home and wait for what they want with a few simple clicks on the websites. The U.S. business-to-consumer e-commerce market is set to suffer a dip in growth in 2020 before rebounding in 2021, powered by essential goods such as grocery and services purchases migrating online as a consequence of COVID-19. Forecasted CGPA for 2019-2023 is 10.5% (J.P.Mogan). Statistically speaking, online shopping seems to surpass physical stores when people make decisions to purchase grocery, and they might spend more money on grocery on websites than purchase in store. However, although online shopping may be more convenient, shoppers still prefer to make their purchases inside an actual store, new research finds. Nearly 40 percent of consumers make purchases inside a physical store at least once a week, compared to just 27 percent who do the same online, according to PwC’s annual consumer survey (Business News Daily).

So this research will investigate if purchasing in different ways will affect amount spend on grocery and implement propensity score matching and multiple linear regression model. And we focus only on grocery because this essential goods which needed by everyone. Our hypothesis is the same customer will spend more money on grocery when they purchase online compare to purchase in store since the growth of online shopping casts a long shadow over a surprising trend: consumers spend significantly more per visit in-store than online. The trend was validated yet again in a recent First Insight Report which found that 71 percent of all shoppers surveyed spent 50 dollars or more when shopping in-store. This compares to only 54 percent of respondents spending more than 50 dollars when shopping online. Emotion plays a role in shopping behavior. There is a human side of in-store shopping and shoppers crave that visceral experience (Petro).

This research is interesting because we will arrive at a statistical model which can forecast the relationship between the people purchase online or in store and the amount they spend on goods. These model predictions will have implications for merchants and customers. The dataset used in this research records customer’s personality and purchasing behaviors. So it is good for making a customer personality analysis for business to better understand its customers and makes it easier for them to modify products according to the specific needs, behaviors and concerns of different types of customers.

Customer behavior analysis helps a business to modify its product based on its target customers from different types of customer segments. For example, instead of spending money to market a new product to every customer in the company’s database, a company can analyze which customer segment is most likely to buy the product and then market the product only on that particular segment. For example, if our hypothesis is accurate then merchant should invest more in online advertisements and in upgrading and maintaining their websites to get customers to purchase. If the prediction is contradict with our hypothesis which indicates customer spend more when they purchase in store then merchants should invest more in store management and maintenance in order to attract customers into the store to purchase.

### Website Overview 


  