---
title: "Plan"

output: 
  html_document:
    toc: true
    toc_float: true
    code_folding: "hide"
---

## Group members (names and uni)
Xuer Liu: xl3371
Jennifer Li: yl5227
Xinyi Zheng: xz3298
Hingling Yu: ay2600

## The tentative project title:
**Swipe or Click: Unraveling the Spending Tug-of-War**

## The motivation for this project:
- In an era where digital storefronts are as common as physical aisles, consumer spending habits have evolved. While online shopping presents a convenience, allowing modern shoppers to indulge from the comfort of their homes, there's an ongoing debate: does this ease translate to more dollars spent? Despite the convenience of digital transactions, a surprising trend persists—shoppers often spend more during physical store visits. 

## The intended final products:
- A website features the project and a screencast that describes our project.
- A page of graphs and charts illustrating the spending patterns, differences in in-store vs online shopping, and other relevant trends, a page for analysis of some factors and approaches we used, a page for report and link to github.
- A detailed analysis report summarizing our findings, methodologies, and implications for both consumers and retailers.

## The anticipated data sources:
- We will utilize a dataset from Kaggle. This dataset includes customer personalities, purchasing behaviors, and specific needs of different customer types. It comprises 2240 observations, providing a robust foundation for our analysis.

## The planned analyses / visualizations / coding challenge:

#### Analyses:
- Hypothesis test (two sample mean test): perform statistical tests to compare average spending amounts between online and in-store purchasers.
- Sensitivity analysis: use sensitivity analysis to test the validity of the project
- Result interpretation: Interpreting the results of our analyses in the context of customer behavior and spending.
#### Visualizations:
- Develop histogram, bar plots and scatter plots to visually represent data trends and model results.

#### Challenges :
- Model fitting: there are some confounding variables that could affect the result of this research such as customers’ income, education level, marital status, and age. So we need to make causal inference on observational dataset by using applicable methods. 


## Planned Timeline
|          Date          |                Descriptions               |
|:----------------------:|:-----------------------------------------:|
| 11/11/2023             | Complete the proposal                     |
| 11/12/2023- 11/15/2023 | Find related dataset to include more variables for customer purchasing behavior. Determine the predictors. Explore and clean the data and discuss which plots we should use.|
| 11/16/2023 | Meeting with TA                                       |
| 11/21/2023- 11/27/2023 | Finish EDA Section, Time Series Plot and analysis linear model part, beginning Interactive World Map.                                     |
| 11/28/2023- 12/05/2023 | Finish the report and video.              |
| 12/09/2023             | Submit!!                                  |

Everyone in the team has contributed to this proposal